apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comax-ledger.fullname" . }}
  labels:
    {{- include "comax-ledger.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "comax-ledger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comax-ledger.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "comax-ledger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-engine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "hyperledger/sawtooth-devmode-engine-rust:chime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - -c
            - "devmode-engine-rust -C tcp://$HOSTNAME:5050"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-settings-tp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: hyperledger/sawtooth-settings-tp:chime
          command:
            - bash
          args:
            - -c
            - "settings-tp -vv -C tcp://$HOSTNAME:4004"
        - name: {{ .Chart.Name }}-intkey-tp-python
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: hyperledger/sawtooth-intkey-tp-python:chime
          command:
            - bash
          args:
            - -c
            - "intkey-tp-python -vv -C tcp://$HOSTNAME:4004"
        - name: {{ .Chart.Name }}-xo-tp-python
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  hyperledger/sawtooth-xo-tp-python:chime
          command:
            - bash
          args:
            - -c
            - "xo-tp-python -vv -C tcp://$HOSTNAME:4004"
        - name: {{ .Chart.Name }}-sawtooth-validator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  hyperledger/sawtooth-validator:chime
          ports:
            - name: tp
              containerPort: 4004
            - name: consensus
              containerPort: 5050
            - name: validators
              containerPort: 8800
          command:
            - bash
          args:
            - -c
            - "sawadm keygen \
            && sawtooth keygen my_key \
            && sawset genesis -k /root/.sawtooth/keys/my_key.priv \
            && sawset proposal create \
              -k /root/.sawtooth/keys/my_key.priv \
              sawtooth.consensus.algorithm.name=Devmode \
              sawtooth.consensus.algorithm.version=0.1 \
              -o config.batch \
            && sawadm genesis config-genesis.batch config.batch \
            && sawtooth-validator -vv \
                --endpoint tcp://$SAWTOOTH_0_SERVICE_HOST:8800 \
                --bind component:tcp://eth0:4004 \
                --bind consensus:tcp://eth0:5050 \
                --bind network:tcp://eth0:8800"
        - name: {{ .Chart.Name }}-rest-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  hyperledger/sawtooth-rest-api:chime
          ports:
            - name: api
              containerPort: 8008
          command:
            - bash
          args:
            - -c
            - "sawtooth-rest-api -C tcp://$HOSTNAME:4004"
        - name: {{ .Chart.Name }}-shell
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  hyperledger/sawtooth-shell:chime
          command:
            - bash
          args:
            - -c
            - "sawtooth keygen && tail -f /dev/null"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
